<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="demo.QtripTests" tests="8" skipped="0" failures="1" errors="0" timestamp="2025-05-31T13:57:23" hostname="GOURAB-LAPTOP" time="134.699">
  <properties/>
  <testcase name="qtrip_non_functional_001" classname="demo.QtripTests" time="4.029"/>
  <testcase name="qtrip_non_functional_002" classname="demo.QtripTests" time="15.65">
    <failure message="java.lang.AssertionError: The following asserts failed:&#10;&#9;expected [400] but found [200]" type="java.lang.AssertionError">java.lang.AssertionError: The following asserts failed:
	expected [400] but found [200]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at demo.QtripTests.qtrip_non_functional_002(QtripTests.java:139)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
  </testcase>
  <testcase name="qtrip_non_functional_003" classname="demo.QtripTests" time="5.613"/>
  <testcase name="qtrip_non_functional_004" classname="demo.QtripTests" time="6.67"/>
  <testcase name="qtrip_non_functional_005" classname="demo.QtripTests" time="10.723"/>
  <testcase name="qtrip_ui_001" classname="demo.QtripTests" time="18.345"/>
  <testcase name="qtrip_ui_002" classname="demo.QtripTests" time="47.713"/>
  <testcase name="qtrip_ui_003" classname="demo.QtripTests" time="25.862"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
